services:
  - type: web
    name: qoraxday-school-app
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_POSTGRES_URL
        sync: false
